### ISSUE TITLE
Is this still a thing?

### ISSUE THREAD

**Issue by RTodorov** [opsgenie/slack-to-opsgenie-alert-creator#1]
Hello there,

Is this project still relevant? What I need to do is to trigger an alert based on a command other than `/genie` so I don't need to change the current process.

Is there any other way that doesn't involve hosting this code somewhere of triggering an alert with a custom command with a message like `/critical everything is down, please help`?

Thank you

**Comment by serhatcan** [comment]
Hey! Yes, the project is still relevant. 

This example involves hosting code. If you want to create your own custom command on Slack to create an alert instead of using /genie alert, you need a way to convert the payload that Slack sends to the structure Opsgenie wants in its alert API. This usually means writing code. 

Hosting is up to you. There are many options that will make it easier but be careful, you probably want it to be reliable. I suggest you go with native integrations if possible like API, monitoring integrations or Slack API which are managed by API and only try this one as the last option. 

Thanks!
